micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/demodb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: Demoroot95.
    schema-generate: update
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
